// FUN_14001a3b0 @ 14001a3b0

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_14001a3b0(undefined8 *param_1,QObject *param_2)

{
  QWidget *pQVar1;
  QAbstractButton *pQVar2;
  bool bVar3;
  QString *pQVar4;
  QSize *pQVar5;
  QGroupBox *pQVar6;
  QRect *pQVar7;
  QPushButton *pQVar8;
  QSizePolicy *pQVar9;
  QCursor *pQVar10;
  QLabel *pQVar11;
  undefined4 local_res8 [2];
  QGroupBox *local_res18;
  QIcon local_res20 [8];
  QFont local_88 [16];
  char *local_78;
  char *pcStack_70;
  QPushButton *local_68;
  void *local_60;
  undefined8 local_58;
  QString local_50 [24];
  
  pQVar4 = (QString *)QObject::objectName(param_2);
  bVar3 = QString::isEmpty(pQVar4);
  QString::~QString(local_50);
  if (bVar3) {
    pcStack_70 = (char *)strnlen("MainView",9);
    local_78 = "MainView";
    QObject::setObjectName(param_2,&local_78);
  }
  QWidget::resize((QWidget *)param_2,0x336,0x11e);
  QIcon::QIcon(local_res20);
  pQVar5 = (QSize *)QSize::QSize((QSize *)&local_res18);
  local_78 = (char *)QByteArrayView::lengthHelperCharArray(":/Resources/Icons/AppIcon.png",0x1e);
  pcStack_70 = QByteArrayView::castHelper(":/Resources/Icons/AppIcon.png");
  pQVar4 = (QString *)QString::fromUtf8(local_50,&local_78);
  QIcon::addFile(local_res20,pQVar4,pQVar5,0,1);
  QString::~QString(local_50);
  QWidget::setWindowIcon((QWidget *)param_2,local_res20);
  QWidget::setWindowOpacity((QWidget *)param_2,_DAT_1400303b8);
  local_78 = (char *)QByteArrayView::lengthHelperCharArray
                               ("#txtEdit_midiCodeView{\n  background-color: #000000;\n}\n\n\n*{\nfont-size:14px;\nfont-weight: bold;\n\n}\nQMainWindow {\n\n  background-color: #151515;\n  color: white;\n  font-family: \"Roboto\"; }\n\n#centralwidget {\n  background-color: #151515; }\nQDialog{\nbackground: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(33, 0, 50), stop: 1 rgb(0, 0, 0));}\nQWidget {\n\n\n  color: white;\n  font-family: \"Roboto\"; }\n\nQGroupBox{\n font-weight: bold;\n  background-color: rgba(36,36,36,210);\n  border-style: transparent;\n  border-radius: 8px;\n}\nQFrame {\n  background-color: #242424;\n  border-style: transparent; }\n\nQGroupBox {\n  padding-top: 10px; }\n  QGroupBox::title {\n\n\n    padding: 8px; }\n\nQMenuBar {\n  background-color: #151515;\n  color: #c0c0c0; }\n  QMenuBar::item {\n    padding: 5px 12px 5px 12px; }\n    QMenuBar::item:selected {\n      background-color: #575757;\n      color: white; }\n    QMenuBar::item:pressed {\n      background-color: #0664c3; }\n\nQMenu {\n  padding-top: 3px;\n  background-color: #2f2f2f; }\n  QMenu::item {\n    padding: 5px 10px 5px 10px;\n    min-width: 180px; }\n    QMenu::item:selected {\n      background-color: #0664c3; }\n\nQLabel {\n  color: #c0c0c0;\n  background-color: transparent; }\n\nQLineEdit,\nQComboBox,\nQSpinBox,\nQDoubleSpinBox {\n  color: #c0c0c0;\n  background-color: black;\n  height: 20px;\n  padding-left: 6px;\n  border-radius: 8px;\n  border: 1px solid #353535; }\n\nQLineEdit:disabled,\nQComboBox:disabled,\nQSpinBox:disabled,\nQDoubleSpinBox :disabled{\n  color: #c0c0c0;\n  background-color: #353535;\n  height: 20px;\n  padding-left: 6px;\n  border-radius: 8px;\n  border: 1px solid black; }\n\n\nQLineEdit:hover,\nQComboBox:hover {\n  border-color: #4f4f4f; }\n\nQLineEdit:focus {\n  border-color: #0664c3; }\n\nQComboBox::drop-down {\n  border: none;\n  padding-right: 5px; }\n\nQComboBox::down-arrow {\n  image: url(:/Resources/Icons/arrow-down.svg);\n  width: 15px; }\n  QComboBox::down-arrow:hover {\n    image: url(:/Resources/Icons/arrow-down-white.svg); }\n\nQSpinBox::up-button,\nQDoubleSpinBox::up-button {\n  image: url(:/Resources/Icons/arrow-up.svg)..." /* TRUNCATED STRING LITERAL */
                                ,0x22bc);
  pcStack_70 = QByteArrayView::castHelper
                         (
                         "#txtEdit_midiCodeView{\n  background-color: #000000;\n}\n\n\n*{\nfont-size:14px;\nfont-weight: bold;\n\n}\nQMainWindow {\n\n  background-color: #151515;\n  color: white;\n  font-family: \"Roboto\"; }\n\n#centralwidget {\n  background-color: #151515; }\nQDialog{\nbackground: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgb(33, 0, 50), stop: 1 rgb(0, 0, 0));}\nQWidget {\n\n\n  color: white;\n  font-family: \"Roboto\"; }\n\nQGroupBox{\n font-weight: bold;\n  background-color: rgba(36,36,36,210);\n  border-style: transparent;\n  border-radius: 8px;\n}\nQFrame {\n  background-color: #242424;\n  border-style: transparent; }\n\nQGroupBox {\n  padding-top: 10px; }\n  QGroupBox::title {\n\n\n    padding: 8px; }\n\nQMenuBar {\n  background-color: #151515;\n  color: #c0c0c0; }\n  QMenuBar::item {\n    padding: 5px 12px 5px 12px; }\n    QMenuBar::item:selected {\n      background-color: #575757;\n      color: white; }\n    QMenuBar::item:pressed {\n      background-color: #0664c3; }\n\nQMenu {\n  padding-top: 3px;\n  background-color: #2f2f2f; }\n  QMenu::item {\n    padding: 5px 10px 5px 10px;\n    min-width: 180px; }\n    QMenu::item:selected {\n      background-color: #0664c3; }\n\nQLabel {\n  color: #c0c0c0;\n  background-color: transparent; }\n\nQLineEdit,\nQComboBox,\nQSpinBox,\nQDoubleSpinBox {\n  color: #c0c0c0;\n  background-color: black;\n  height: 20px;\n  padding-left: 6px;\n  border-radius: 8px;\n  border: 1px solid #353535; }\n\nQLineEdit:disabled,\nQComboBox:disabled,\nQSpinBox:disabled,\nQDoubleSpinBox :disabled{\n  color: #c0c0c0;\n  background-color: #353535;\n  height: 20px;\n  padding-left: 6px;\n  border-radius: 8px;\n  border: 1px solid black; }\n\n\nQLineEdit:hover,\nQComboBox:hover {\n  border-color: #4f4f4f; }\n\nQLineEdit:focus {\n  border-color: #0664c3; }\n\nQComboBox::drop-down {\n  border: none;\n  padding-right: 5px; }\n\nQComboBox::down-arrow {\n  image: url(:/Resources/Icons/arrow-down.svg);\n  width: 15px; }\n  QComboBox::down-arrow:hover {\n    image: url(:/Resources/Icons/arrow-down-white.svg); }\n\nQSpinBox::up-button,\nQDoubleSpinBox::up-button {\n  image: url(:/Resources/Icons/arrow-up.svg)..." /* TRUNCATED STRING LITERAL */
                         );
  pQVar4 = (QString *)QString::fromUtf8(local_50,&local_78);
  QWidget::setStyleSheet((QWidget *)param_2,pQVar4);
  QString::~QString(local_50);
  QDialog::setSizeGripEnabled((QDialog *)param_2,false);
  QDialog::setModal((QDialog *)param_2,false);
  pQVar6 = (QGroupBox *)FUN_140022d40(0x28);
  local_res18 = pQVar6;
  QGroupBox::QGroupBox(pQVar6,(QWidget *)param_2);
  *(undefined ***)pQVar6 = QGroupBox::vftable;
  *(undefined ***)(pQVar6 + 0x10) = QGroupBox::vftable;
  *param_1 = pQVar6;
  pcStack_70 = (char *)strnlen("gb_ota_upgrade",0xf);
  local_78 = "gb_ota_upgrade";
  QObject::setObjectName((QObject *)pQVar6,&local_78);
  pQVar1 = (QWidget *)*param_1;
  pQVar7 = (QRect *)QRect::QRect((QRect *)&local_78,0x14,0xa0,0x30d,0x6f);
  QWidget::setGeometry(pQVar1,pQVar7);
  pQVar8 = (QPushButton *)FUN_140022d40(0x28);
  local_res18 = (QGroupBox *)pQVar8;
  QPushButton::QPushButton(pQVar8,(QWidget *)*param_1);
  *(undefined ***)pQVar8 = QPushButton::vftable;
  *(undefined ***)(pQVar8 + 0x10) = QPushButton::vftable;
  param_1[1] = pQVar8;
  pcStack_70 = (char *)strnlen("btn_uf",7);
  local_78 = "btn_uf";
  QObject::setObjectName((QObject *)pQVar8,&local_78);
  pQVar1 = (QWidget *)param_1[1];
  pQVar7 = (QRect *)QRect::QRect((QRect *)&local_78,10,0x46,0xb5,0x20);
  QWidget::setGeometry(pQVar1,pQVar7);
  QSizePolicy::QSizePolicy((QSizePolicy *)local_res8,1,1,1);
  QSizePolicy::setHorizontalStretch((QSizePolicy *)local_res8,0);
  QSizePolicy::setVerticalStretch((QSizePolicy *)local_res8,0);
  pQVar9 = (QSizePolicy *)QWidget::sizePolicy((QWidget *)param_1[1]);
  bVar3 = QSizePolicy::hasHeightForWidth(pQVar9);
  QSizePolicy::setHeightForWidth((QSizePolicy *)local_res8,bVar3);
  QWidget::setSizePolicy((QWidget *)param_1[1],local_res8[0]);
  pQVar1 = (QWidget *)param_1[1];
  pQVar5 = (QSize *)QSize::QSize((QSize *)&local_res18,0x20,0x20);
  QWidget::setMinimumSize(pQVar1,pQVar5);
  QFont::QFont(local_88);
  local_78 = (char *)QByteArrayView::lengthHelperCharArray("Roboto",7);
  pcStack_70 = QByteArrayView::castHelper("Roboto");
  QString::fromUtf8(local_50,&local_78);
  local_60 = QArrayData::allocate((QArrayData **)&local_res18,0x18,8,1,1);
  local_68 = (QPushButton *)local_res18;
  local_58 = 0;
  FUN_140015970((longlong)&local_68,local_50,(QString *)&stack0xffffffffffffffc8);
  QFont::setFamilies(local_88,(QList<QString> *)&local_68);
  FUN_1400078e0(&local_68);
  _eh_vector_destructor_iterator_(local_50,0x18,1,~QString_exref);
  QFont::setWeight(local_88,700);
  QWidget::setFont((QWidget *)param_1[1],local_88);
  pQVar1 = (QWidget *)param_1[1];
  pQVar10 = (QCursor *)QCursor::QCursor((QCursor *)&local_res18,0xd);
  QWidget::setCursor(pQVar1,pQVar10);
  QCursor::~QCursor((QCursor *)&local_res18);
  QWidget::setAttribute((QWidget *)param_1[1],2,true);
  QWidget::setLayoutDirection((QWidget *)param_1[1],1);
  QWidget::setAutoFillBackground((QWidget *)param_1[1],false);
  pQVar1 = (QWidget *)param_1[1];
  local_78 = (char *)QByteArrayView::lengthHelperCharArray("",1);
  pcStack_70 = QByteArrayView::castHelper("");
  pQVar4 = (QString *)QString::fromUtf8(local_50,&local_78);
  QWidget::setStyleSheet(pQVar1,pQVar4);
  QString::~QString(local_50);
  pQVar2 = (QAbstractButton *)param_1[1];
  pQVar5 = (QSize *)QSize::QSize((QSize *)&local_res18,0x20,0x20);
  QAbstractButton::setIconSize(pQVar2,pQVar5);
  QPushButton::setFlat((QPushButton *)param_1[1],false);
  pQVar8 = (QPushButton *)FUN_140022d40(0x28);
  local_res18 = (QGroupBox *)pQVar8;
  QPushButton::QPushButton(pQVar8,(QWidget *)*param_1);
  *(undefined ***)pQVar8 = QPushButton::vftable;
  *(undefined ***)(pQVar8 + 0x10) = QPushButton::vftable;
  param_1[2] = pQVar8;
  pcStack_70 = (char *)strnlen("btn_sf",7);
  local_78 = "btn_sf";
  QObject::setObjectName((QObject *)pQVar8,&local_78);
  pQVar1 = (QWidget *)param_1[2];
  pQVar7 = (QRect *)QRect::QRect((QRect *)&local_78,10,0x1e,0xb5,0x20);
  QWidget::setGeometry(pQVar1,pQVar7);
  pQVar9 = (QSizePolicy *)QWidget::sizePolicy((QWidget *)param_1[2]);
  bVar3 = QSizePolicy::hasHeightForWidth(pQVar9);
  QSizePolicy::setHeightForWidth((QSizePolicy *)local_res8,bVar3);
  QWidget::setSizePolicy((QWidget *)param_1[2],local_res8[0]);
  pQVar1 = (QWidget *)param_1[2];
  pQVar5 = (QSize *)QSize::QSize((QSize *)&local_res18,0x20,0x20);
  QWidget::setMinimumSize(pQVar1,pQVar5);
  QWidget::setFont((QWidget *)param_1[2],local_88);
  pQVar1 = (QWidget *)param_1[2];
  pQVar10 = (QCursor *)QCursor::QCursor((QCursor *)&local_res18,0xd);
  QWidget::setCursor(pQVar1,pQVar10);
  QCursor::~QCursor((QCursor *)&local_res18);
  QWidget::setAttribute((QWidget *)param_1[2],2,true);
  QWidget::setLayoutDirection((QWidget *)param_1[2],1);
  QWidget::setAutoFillBackground((QWidget *)param_1[2],false);
  pQVar1 = (QWidget *)param_1[2];
  local_78 = (char *)QByteArrayView::lengthHelperCharArray("",1);
  pcStack_70 = QByteArrayView::castHelper("");
  pQVar4 = (QString *)QString::fromUtf8(local_50,&local_78);
  QWidget::setStyleSheet(pQVar1,pQVar4);
  QString::~QString(local_50);
  pQVar2 = (QAbstractButton *)param_1[2];
  pQVar5 = (QSize *)QSize::QSize((QSize *)&local_res18,0x20,0x20);
  QAbstractButton::setIconSize(pQVar2,pQVar5);
  QPushButton::setFlat((QPushButton *)param_1[2],false);
  pQVar11 = (QLabel *)FUN_140022d40(0x28);
  local_res18 = (QGroupBox *)pQVar11;
  QLabel::QLabel(pQVar11,*param_1,0);
  *(undefined ***)pQVar11 = QLabel::vftable;
  *(undefined ***)(pQVar11 + 0x10) = QLabel::vftable;
  param_1[3] = pQVar11;
  pcStack_70 = (char *)strnlen("lbl_sotaf",10);
  local_78 = "lbl_sotaf";
  QObject::setObjectName((QObject *)pQVar11,&local_78);
  pQVar1 = (QWidget *)param_1[3];
  pQVar7 = (QRect *)QRect::QRect((QRect *)&local_78,0xd2,0x1e,0x227,0x20);
  QWidget::setGeometry(pQVar1,pQVar7);
  pQVar11 = (QLabel *)FUN_140022d40(0x28);
  local_res18 = (QGroupBox *)pQVar11;
  QLabel::QLabel(pQVar11,*param_1,0);
  *(undefined ***)pQVar11 = QLabel::vftable;
  *(undefined ***)(pQVar11 + 0x10) = QLabel::vftable;
  param_1[4] = pQVar11;
  pcStack_70 = (char *)strnlen("lbl_ufLabel",0xc);
  local_78 = "lbl_ufLabel";
  QObject::setObjectName((QObject *)pQVar11,&local_78);
  pQVar1 = (QWidget *)param_1[4];
  pQVar7 = (QRect *)QRect::QRect((QRect *)&local_78,0xd2,0x46,0x227,0x20);
  QWidget::setGeometry(pQVar1,pQVar7);
  pQVar6 = (QGroupBox *)FUN_140022d40(0x28);
  local_res18 = pQVar6;
  QGroupBox::QGroupBox(pQVar6,(QWidget *)param_2);
  *(undefined ***)pQVar6 = QGroupBox::vftable;
  *(undefined ***)(pQVar6 + 0x10) = QGroupBox::vftable;
  param_1[5] = pQVar6;
  pcStack_70 = (char *)strnlen("groupBox",9);
  local_78 = "groupBox";
  QObject::setObjectName((QObject *)pQVar6,&local_78);
  pQVar1 = (QWidget *)param_1[5];
  pQVar7 = (QRect *)QRect::QRect((QRect *)&local_78,0x14,0x14,0x30d,0x79);
  QWidget::setGeometry(pQVar1,pQVar7);
  pQVar11 = (QLabel *)FUN_140022d40(0x28);
  local_res18 = (QGroupBox *)pQVar11;
  QLabel::QLabel(pQVar11,param_1[5],0);
  *(undefined ***)pQVar11 = QLabel::vftable;
  *(undefined ***)(pQVar11 + 0x10) = QLabel::vftable;
  param_1[6] = pQVar11;
  pcStack_70 = (char *)strnlen("lbl_waitDeviceConnect",0x16);
  local_78 = "lbl_waitDeviceConnect";
  QObject::setObjectName((QObject *)pQVar11);
  pQVar1 = (QWidget *)param_1[6];
  pQVar7 = (QRect *)QRect::QRect((QRect *)&local_78,0,0x14,0x30d,0x46);
  QWidget::setGeometry(pQVar1,pQVar7);
  pQVar1 = (QWidget *)param_1[6];
  local_78 = (char *)QByteArrayView::lengthHelperCharArray
                               ("font-size:35px;\nfont-weight:900;\ncolor:rgb(255,255,255);",0x39);
  pcStack_70 = QByteArrayView::castHelper
                         ("font-size:35px;\nfont-weight:900;\ncolor:rgb(255,255,255);");
  pQVar4 = (QString *)QString::fromUtf8(local_50,&local_78);
  QWidget::setStyleSheet(pQVar1,pQVar4);
  QString::~QString(local_50);
  QLabel::setAlignment((QLabel *)param_1[6],0x84);
  FUN_14001a020(param_1,(QWidget *)param_2);
  QMetaObject::connectSlotsByName(param_2);
  QFont::~QFont(local_88);
  QIcon::~QIcon(local_res20);
  return;
}


